version: "3.2"

services:
  app:
    container_name: python-telebot
    build: ./python
    volumes:
      - ./python:/python
    restart: unless-stopped

  restarter:
    container_name: restarter
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart python-telebot; done"]
    restart: unless-stopped
